### ISSUE TITLE
You must delete this repository ASAP

### ISSUE THREAD

**Issue by Stereoarts** [newwers/DesktopPet#1]
Did you check all model licenses?
您检查了所有型号许可证吗？

You can't use / upload almost models.
您无法使用/上传几乎所有型号。

readme.txt in KizunaAI_ver1.01.zip
1.データを再配布すること。(1. You can't redistribute my data.)

https://github.com/newwers/DesktopPet/blob/master/Assets/_MyModels/kangna/Readme_English.txt
No re-distribution

https://github.com/newwers/DesktopPet/blob/master/Assets/_MyModels/l60z38131z/q%E7%89%88%E5%8B%BF%E5%BF%98/Readme.txt
・元データの再配布はご遠慮下さい。(- You can't redistribute my works.)

https://github.com/newwers/DesktopPet/blob/master/Assets/_MyModels/l60z38131z/q%E7%89%88%E5%B1%B1%E5%90%B9/Readme.txt
・元データの再配布はご遠慮下さい。(- You can't redistribute my works.)

https://github.com/newwers/DesktopPet/blob/master/Assets/_MyModels/l60z38131z/q%E7%89%88%E7%99%BD%E7%BB%83/Readme.txt
・元データの再配布はご遠慮下さい。(- You can't redistribute my works.)

https://github.com/newwers/DesktopPet/blob/master/Assets/_MyModels/l60z38131z/q%E7%89%88%E7%AC%A6%E5%8D%8E/Readme.txt
・元データの再配布はご遠慮下さい。(- You can't redistribute my works.)

https://github.com/newwers/DesktopPet/blob/master/Assets/_MyModels/l60z38131z/q%E7%89%88%E7%BB%AF%E7%BA%A2/Readme.txt
・元データの再配布はご遠慮下さい。(- You can't redistribute my works.)

https://github.com/newwers/DesktopPet/blob/master/Assets/_MyModels/l60z38131z/q%E7%89%88%E7%BB%AF%E7%BA%A2/Readme.txt
・元データの再配布はご遠慮下さい。(- You can't redistribute my works.)

https://github.com/newwers/DesktopPet/blob/master/Assets/_MyModels/l60z38131z/q%E7%89%88%E8%AA%93%E7%BA%A6/Readme.txt
・元データの再配布はご遠慮下さい。(- You can't redistribute my works.)

**Comment by Stereoarts** [comment]
If you can't compliance it, I'll never support all oversea's developers.
如果你不能遵守它，我永远不会支持所有海外的开发者。

**Comment by Stereoarts** [comment]
Also they aren't pet! I hate you.
他们也不是宠物！ 我恨你。

**Comment by newwers** [comment]
Sorry,I didn't know I couldn't upload the model.I will delete them immediately.Sorry
不好意思，我不知道不能上传这些模型，我会立刻将所有模型都删除掉.
